version: '3'

services:
  nestjs:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        NODE_VERSION: ${NODE_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
    restart: unless-stopped
    volumes:
      - "..:/nestjs:rw"
      - "nestjs_demo-node_modules:/nestjs/node_modules"
    ports:
      - 3000:3000

  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: fullstackpanama2021

volumes:
    nestjs_demo-node_modules:
